<a href="https://colab.research.google.com/github/BFvandy/EV_Buzz_Analysis/blob/main/EV_SW_DataCollection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
cur_path = "/content/drive/My Drive/EV Buzz Analysis/Strategic Window Verbatim/Separate Data Files"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/EV Buzz Analysis/Strategic Window Verbatim/Separate Data Files

In [ ]:
ev_2022_sw = pd.read_csv('EV_2022_SW.csv', skiprows=12)
ev_2021_sw = pd.read_csv('EV_2021_SW.csv', skiprows=12)
ev_2020_sw = pd.read_csv('EV_2020_SW.csv', skiprows=12)

In [ ]:
frames = [ev_2022_sw, ev_2021_sw, ev_2020_sw]
ev_sw = pd.concat(frames)

In [ ]:
ev_sw = ev_sw.reset_index(drop=True)

In [ ]:
ev_sw

,Purchased,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Nissan Leaf S Plus,2022,(None),NaN,Chevrolet Bolt EV,2022.0,Sentiment Not Calculated,Age 47,Male,White,"$65,001 - $70,000",It's a great commuter car. It's comfortable an...
1,Volkswagen ID.4 AWD,2021,BMW X3 xDrive 30e,2018.0,Hyundai Kona,2021.0,Sentiment Not Calculated,Age 58,Male,White,"$200,001 - $300,000",LOVE THE CAR BUT...\n1) Dealer was dishonest a...
2,Tesla Model 3,2022,(None),NaN,Tesla Model 3,2019.0,Sentiment Not Calculated,Age 45,Male,White,"$65,001 - $70,000",The range and energy efficiency is excellent- ...
3,Volkswagen ID.4 AWD,2021,Toyota RAV4,2016.0,Volvo C40,2021.0,Sentiment Not Calculated,Age 74,Male,White,"$300,001 - $400,000",I preordered using the VW online site December...
4,Tesla Model 3,2022,Nissan Maxima,1995.0,Ford Mustang Mach-E,2022.0,Sentiment Not Calculated,Age 72,Male,NaN,"$80,001 - $90,000",I just finished my trip in my 2022 Model 3 lon...
...,...,...,...,...,...,...,...,...,...,...,...,...
22511,Tesla Model 3,2020,Volkswagen Passat / New Passat,2017.0,Hyundai Kona,2020.0,Sentiment Not Calculated,Age 24,Male,White,"$60,001 - $65,000",No
22512,Chevrolet Bolt EV,2020,GMC Acadia,2017.0,Tesla Model S,2020.0,Sentiment Not Calculated,Age 61,Male,White,"$300,001 - $400,000",No
22513,Nissan Leaf SV Plus,2019,Volvo S60 Sedan,2012.0,Volvo XC40,2020.0,Sentiment Not Calculated,Age 67,Female,White,"$90,001 - $100,000",No
22514,Chevrolet Bolt EV,2020,Chevrolet Bolt EV,2017.0,(None),NaN,Sentiment Not Calculated,Age 47,Male,Other,"$500,001 - $750,000",No
22515,Nissan Leaf SV Plus,2019,Jeep Patriot,2013.0,Tesla Model S,2019.0,Sentiment Not Calculated,Age 43,Male,White,"$100,001 - $125,000",No

In [ ]:
ev_sw.groupby(['Purchased']).count()

,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
Purchased,,,,,,,,,,,
Chevrolet Bolt EV,1887,1887,1303,1887,1038,1887,1887,1887,1838,1887,1884
Ford Mustang Mach-E AWD,1176,1176,800,1176,710,1176,1176,1176,1113,1176,1175
Ford Mustang Mach-E RWD,529,529,366,529,315,529,529,529,497,529,528
GMC Hummer Pickup,11,11,1,11,1,11,11,11,11,11,11
Hyundai Ioniq 5 AWD,250,250,182,250,192,250,250,250,230,250,250
Hyundai Ioniq 5 RWD,224,224,162,224,166,224,224,224,208,224,223
Hyundai Kona EV Limited,537,537,367,537,374,537,537,537,524,537,537
Hyundai Kona EV SEL,471,471,326,471,312,471,471,471,454,471,469
Hyundai Kona EV Ultimate,476,476,348,476,320,476,476,476,466,476,474
Kia EV6 AWD,438,438,320,438,302,438,438,438,407,438,438
Kia EV6 RWD,90,90,62,90,47,90,90,90,86,90,90
Nissan Leaf S,551,551,282,551,319,551,551,551,524,551,548
Nissan Leaf S Plus,647,647,371,647,433,647,647,647,609,647,647
Nissan Leaf SL,10,10,7,10,7,10,10,10,7,10,10
Nissan Leaf SL Plus,953,953,633,953,662,953,953,953,912,953,952
Nissan Leaf SV,1020,1020,563,1020,554,1020,1020,1020,987,1020,1018
Nissan Leaf SV Plus,1104,1104,699,1104,698,1104,1104,1104,1063,1104,1101
Rivian R1T,10,10,7,10,0,10,10,10,10,10,10
Tesla Model 3,5411,5411,3447,5411,2206,5411,5411,5411,5254,5411,5397
Tesla Model Y,5070,5070,3382,5070,2340,5070,5070,5070,4901,5070,5058
Volkswagen ID.4 AWD,629,629,438,629,417,629,629,629,582,629,629
Volkswagen ID.4 RWD,1022,1022,748,1022,725,1022,1022,1022,1000,1022,1021

In [ ]:
import os
cur_path = "/content/drive/My Drive/EV Buzz Analysis/Strategic Window Verbatim"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/EV Buzz Analysis/Strategic Window Verbatim

In [ ]:
ev_sw.to_csv('EV_SW_3yrs.csv', index = 'False')